### ISSUE TITLE
can't find the database

### ISSUE THREAD

**Issue by SherlockHolmes29** [DevMilk/Fatigue-Voice-Analysis-Project#3]
when i run the "TrainModelGoogleColab.ipynb"
[Errno 2] No such file or directory: 'gdrive/My Drive/MatlabSpectrogram'/content
why?
(sorry,my English is very poor)

**Comment by DevMilk** [comment]
I was using a database from my google drive account which contains voice spectrogram images and given permission to access from professors at my university, you dont have that on your google drive thats the reason

**Comment by SherlockHolmes29** [comment]
OK,thank you.
Do you mind share this database with me?
I'm a student from China,I want to do some research about how to detect fatigue from voice,but i can't find a database.
I guarantee that this database is for research purposes only.
My E-mail is nainainainainai999@gmail.com.

**Comment by DevMilk** [comment]
I would like to share but i dont have access to it currently either, data was collected by professors from my university by getting many students' voice and converting their voice to spectrogram by matlab. After i finished my project, they said they are going to edit data so they cut access to their drive folder. But i would like to help you if you got any questions :)

**Comment by SherlockHolmes29** [comment]
Thank you very much.
